// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dmruxptaufrqhyjszgdm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRtcnV4cHRhdWZycWh5anN6Z2RtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MTI2NjgsImV4cCI6MjA2OTI4ODY2OH0.LGAzXcBphC98Ny8nD_0-iA1r5E4hTGvYL0ydQUGbf40";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});